#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
Script para cargar el catálogo inicial de entes públicos
"""

import sys
import os

# Agregar el directorio padre al path
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))

from app import create_app
from models import db, Ente

# Datos de entes a cargar
ENTES_DATA = [
    ("1", "ENTE_1", "PODER EJECUTIVO DEL ESTADO DE TLAXCALA", "EJECUTIVO", "PODER DEL ESTADO", "ESTATAL"),
    ("1.1", "ENTE_1_1", "DESPACHO DE LA GOBERNADORA", "DG", "DEPENDENCIA", "ESTATAL"),
    ("1.2", "ENTE_1_2", "SECRETARÍA DE GOBIERNO", "SEGOB", "DEPENDENCIA", "ESTATAL"),
    ("1.3", "ENTE_1_3", "OFICIALIA MAYOR DE GOBIERNO", "OMG", "DEPENDENCIA", "ESTATAL"),
    ("1.4", "ENTE_1_4", "SECRETARÍA DE FINANZAS", "SF", "DEPENDENCIA", "ESTATAL"),
    ("1.5", "ENTE_1_5", "SECRETARÍA DE DESARROLLO ECONOMICO", "SEDECO", "DEPENDENCIA", "ESTATAL"),
    ("1.6", "ENTE_1_6", "SECRETARÍA DE TURISMO", "SECTUR", "DEPENDENCIA", "ESTATAL"),
    ("1.7", "ENTE_1_7", "SECRETARÍA DE INFRAESTRUCTURA", "SI", "DEPENDENCIA", "ESTATAL"),
    ("1.8", "ENTE_1_8", "SECRETARÍA DE EDUCACIÓN PÚBLICA", "SEPE", "DEPENDENCIA", "ESTATAL"),
    ("1.9", "ENTE_1_9", "SECRETARÍA DE MOVILIDAD Y TRANSPORTE", "SMYT", "DEPENDENCIA", "ESTATAL"),
    ("1.10.", "ENTE_1_10", "SECRETARÍA DE LA FUNCIÓN PÚBLICA", "SFP", "DEPENDENCIA", "ESTATAL"),
    ("1.11", "ENTE_1_11", "SECRETARÍA DE IMPULSO AGROPECUARIO", "SIA", "DEPENDENCIA", "ESTATAL"),
    ("1.12", "ENTE_1_12", "COORDINACIÓN DE COMUNICACIÓN", "CCOM", "DEPENDENCIA", "ESTATAL"),
    ("1.13", "ENTE_1_13", "SECRETARÍA DE MEDIO AMBIENTE", "SMA", "DEPENDENCIA", "ESTATAL"),
    ("1.14", "ENTE_1_14", "SECRETARÍA DE CULTURA", "SC", "DEPENDENCIA", "ESTATAL"),
    ("1.15", "ENTE_1_15", "SECRETARÍA DE LAS MUJERES", "SMET", "DEPENDENCIA", "ESTATAL"),
    ("1.16", "ENTE_1_16", "SECRETARÍA DE ORDENAMIENTO TERRITORIAL Y VIVIENDA", "SOTYV", "DEPENDENCIA", "ESTATAL"),
    ("1.17", "ENTE_1_17", "SECRETARÍA DE SEGURIDAD CIUDADANA", "SSC", "DEPENDENCIA", "ESTATAL"),
    ("1.18", "ENTE_1_18", "COORDINACIÓN GENERAL DE PLANEACIÓN E INVERSIÓN", "CGPI", "DEPENDENCIA", "ESTATAL"),
    ("1.19", "ENTE_1_19", "SECRETARÍA DE BIENESTAR", "SB", "DEPENDENCIA", "ESTATAL"),
    ("1.20.", "ENTE_1_20", "SECRETARÍA DE TRABAJO Y COMPETITIVIDAD", "STYC", "DEPENDENCIA", "ESTATAL"),
    ("1.21", "ENTE_1_21", "CONSEJERÍA JURÍDICA DEL EJECUTIVO", "CJE", "DEPENDENCIA", "ESTATAL"),
    ("1.22", "ENTE_1_22", "COORDINACIÓN ESTATAL DE PROTECCIÓN CIVIL", "CEPC", "DESCONCENTRADOS", "ESTATAL"),
    ("1.23", "ENTE_1_23", "SECRETARIADO EJECUTIVO DEL SISTEMA ESTATAL DE SEGURIDAD PÚBLICA", "SESESP", "DESCONCENTRADOS", "ESTATAL"),
    ("1.24", "ENTE_1_24", "INSTITUTO TLAXCALTECA DE DESARROLLO TAURINO", "ITDT", "DESCONCENTRADOS", "ESTATAL"),
    ("1.25", "ENTE_1_25", "INSTITUTO TLAXCALTECA DE ASISTENCIA ESPECIALIZADA A LA SALUD", "ITAES", "DESCONCENTRADOS", "ESTATAL"),
    ("1.26", "ENTE_1_26", "COMISIÓN ESTATAL DE ARBITRAJE MÉDICO", "CEAM", "DESCONCENTRADOS", "ESTATAL"),
    ("1.27", "ENTE_1_27", "CASA DE LAS ARTESANÍAS DE TLAXCALA", "CAT", "DESCONCENTRADOS", "ESTATAL"),
    ("1.28", "ENTE_1_28", "PROCURADURÍA DE PROTECCIÓN AL AMBIENTE DEL ESTADO DE TLAXCALA", "PROPAET", "DESCONCENTRADOS", "ESTATAL"),
    ("1.29", "ENTE_1_29", "INSTITUTO DE FAUNA SILVESTRE PARA EL ESTADO DE TLAXCALA", "IFAST", "DESCONCENTRADOS", "ESTATAL"),
    ("2", "ENTE_2", "PODER LEGISLATIVO DEL ESTADO DE TLAXCALA", "LEGISLATIVO", "PODERES DEL ESTADO", "ESTATAL"),
    ("3", "ENTE_3", "PODER JUDICIAL DEL ESTADO DE TLAXCALA", "PJET", "PODERES DEL ESTADO", "ESTATAL"),
    ("4", "ENTE_4", "CENTRO DE CONCILIACIÓN LABORAL DEL ESTADO DE TLAXCALA", "CCLET", "DESCENTRALIZADO/PARAESTATAL", "ESTATAL"),
    ("5", "ENTE_5", "COMISIÓN ESTATAL DEL AGUA Y SANEAMIENTO DEL ESTADO DE TLAXCALA", "CEAS", "DESCENTRALIZADO/PARAESTATAL", "ESTATAL"),
    ("6", "ENTE_6", "COLEGIO DE BACHILLERES DEL ESTADO DE TLAXCALA", "COBAT", "DESCENTRALIZADO/PARAESTATAL", "ESTATAL"),
    ("7", "ENTE_7", "COLEGIO DE EDUCACIÓN PROFESIONAL TÉCNICA DEL ESTADO DE TLAXCALA", "CONALEP", "DESCENTRALIZADO/PARAESTATAL", "ESTATAL"),
    ("8", "ENTE_8", "COLEGIO DE ESTUDIOS CIENTÍFICOS Y TECNOLÓGICOS DEL ESTADO DE TLAXCALA", "CECYTE", "DESCENTRALIZADO/PARAESTATAL", "ESTATAL"),
    ("9", "ENTE_9", "CONSEJO ESTATAL DE POBLACIÓN", "COESPO", "DESCENTRALIZADO/PARAESTATAL", "ESTATAL"),
    ("10", "ENTE_10", "COORDINACIÓN DE RADIO, CINE Y TELEVISIÓN", "CORACYT", "DESCENTRALIZADO/PARAESTATAL", "ESTATAL"),
    ("11", "ENTE_11", "EL COLEGIO DE TLAXCALA, A.C.", "COLTLAX", "DESCENTRALIZADO/PARAESTATAL", "ESTATAL"),
    ("12", "ENTE_12", "FIDEICOMISO DE LA CIUDAD INDUSTRIAL DE XICOTÉNCATL", "FIDECIX", "DESCENTRALIZADO/PARAESTATAL", "ESTATAL"),
    ("13", "ENTE_13", "COMISIÓN EJECUTIVA DE ATENCIÓN A VÍCTIMAS DEL ESTADO DE TLAXCALA", "CEAVIT", "DESCENTRALIZADO/PARAESTATAL", "ESTATAL"),
    ("14", "ENTE_14", "FONDO MACRO PARA EL DESARROLLO INTEGRAL DE TLAXCALA", "FOMTLAX", "DESCENTRALIZADO/PARAESTATAL", "ESTATAL"),
    ("15", "ENTE_15", "INSTITUTO DE CAPACITACIÓN PARA EL TRABAJO DEL ESTADO DE TLAXCALA", "ICATLAX", "DESCENTRALIZADO/PARAESTATAL", "ESTATAL"),
    ("16", "ENTE_16", "INSTITUTO DE CATASTRO DEL ESTADO DE TLAXCALA", "IDC", "DESCENTRALIZADO/PARAESTATAL", "ESTATAL"),
    ("17", "ENTE_17", "INSTITUTO DEL DEPORTE DE TLAXCALA", "IDET", "DESCENTRALIZADO/PARAESTATAL", "ESTATAL"),
    ("18", "ENTE_18", "INSTITUTO TECNOLÓGICO SUPERIOR DE TLAXCO", "ITST", "DESCENTRALIZADO/PARAESTATAL", "ESTATAL"),
    ("19", "ENTE_19", "INSTITUTO TLAXCALTECA DE LA INFRAESTRUCTURA FÍSICA EDUCATIVA", "ITIFE", "DESCENTRALIZADO/PARAESTATAL", "ESTATAL"),
    ("20", "ENTE_20", "INSTITUTO TLAXCALTECA DE LA JUVENTUD", "ITJ", "DESCENTRALIZADO/PARAESTATAL", "ESTATAL"),
    ("21", "ENTE_21", "INSTITUTO TLAXCALTECA PARA LA EDUCACIÓN DE LOS ADULTOS, ITEA", "ITEA", "DESCENTRALIZADO/PARAESTATAL", "ESTATAL"),
    ("22", "ENTE_22", "ÓRGANISMO PÚBLICO DESCENTRALIZADO SALUD DE TLAXCALA", "OPD_SALUD", "DESCENTRALIZADO/PARAESTATAL", "ESTATAL"),
    ("23", "ENTE_23", "PATRONATO CENTRO DE REHABILITACIÓN INTEGRAL Y ESCUELA EN TERAPIA FÍSICA Y REHABILITACIÓN", "CRI-ESCUELA", "DESCENTRALIZADO/PARAESTATAL", "ESTATAL"),
    ("24", "ENTE_24", "PATRONATO \"LA LIBERTAD CENTRO CULTURAL DE APIZACO\"", "LA_LIBERTAD", "DESCENTRALIZADO/PARAESTATAL", "ESTATAL"),
    ("25", "ENTE_25", "PENSIONES CIVILES DEL ESTADO DE TLAXCALA", "PCET", "DESCENTRALIZADO/PARAESTATAL", "ESTATAL"),
    ("26", "ENTE_26", "SISTEMA ESTATAL PARA EL DESARROLLO INTEGRAL DE LA FAMILIA", "SEDIF", "DESCENTRALIZADO/PARAESTATAL", "ESTATAL"),
    ("27", "ENTE_27", "UNIDAD DE SERVICIOS EDUCATIVOS DEL ESTADO DE TLAXCALA", "USET", "DESCENTRALIZADO/PARAESTATAL", "ESTATAL"),
    ("28", "ENTE_28", "UNIVERSIDAD POLITÉCNICA DE TLAXCALA", "UPT", "DESCENTRALIZADO/PARAESTATAL", "ESTATAL"),
    ("29", "ENTE_29", "UNIVERSIDAD POLITÉCNICA DE TLAXCALA REGIÓN PONIENTE", "UPTREP", "DESCENTRALIZADO/PARAESTATAL", "ESTATAL"),
    ("30", "ENTE_30", "UNIVERSIDAD TECNOLÓGICA DE TLAXCALA", "UTT", "DESCENTRALIZADO/PARAESTATAL", "ESTATAL"),
    ("31", "ENTE_31", "UNIVERSIDAD INTERCULTURAL DE TLAXCALA", "UIT", "DESCENTRALIZADO/PARAESTATAL", "ESTATAL"),
    ("32", "ENTE_32", "ARCHIVO GENERAL E HISTORICO DEL ESTADO DE TLAXCALA", "AGHET", "DESCENTRALIZADO/PARAESTATAL", "ESTATAL"),
    ("33", "ENTE_33", "TRIBUNAL DE JUSTICIA ADMINISTRATIVA DEL ESTADO DE TLAXCALA", "TJA", "ORGANISMO AUTÓNOMO", "ESTATAL"),
    ("34", "ENTE_34", "UNIVERSIDAD AUTÓNOMA DE TLAXCALA", "UAT", "ORGANISMO AUTÓNOMO", "ESTATAL"),
    ("35", "ENTE_35", "COMISIÓN ESTATAL DE DERECHOS HUMANOS", "CEDH", "ORGANISMO AUTÓNOMO", "ESTATAL"),
    ("36", "ENTE_36", "INSTITUTO TLAXCALTECA DE ELECCIONES", "ITE", "ORGANISMO AUTÓNOMO", "ESTATAL"),
    ("37", "ENTE_37", "INSTITUTO DE ACCESO A LA INFORMACIÓN PÚBLICA Y PROTECCIÓN DE DATOS PERSONALES DEL ESTADO DE TLAXCALA", "IAIP", "ORGANISMO AUTÓNOMO", "ESTATAL"),
    ("38", "ENTE_38", "TRIBUNAL DE CONCILIACIÓN Y ARBITRAJE DEL ESTADO DE TLAXCALA", "TCYA", "ORGANISMO AUTÓNOMO", "ESTATAL"),
    ("39", "ENTE_39", "TRIBUNAL ELECTORAL DE TLAXCALA", "TET", "ORGANISMO AUTÓNOMO", "ESTATAL"),
    ("40", "ENTE_40", "FISCALÍA GENERAL DE JUSTICIA DEL ESTADO DE TLAXCALA", "FGJET", "ORGANISMO AUTÓNOMO", "ESTATAL"),
    ("41", "ENTE_41", "SECRETARIA EJECUTIVA DEL SISTEMA ANTICORRUPCIÓN DEL ESTADO DE TLAXCALA", "SESAET", "ORGANISMO DESCENTRALIZADO NO SECTORIZADO", "ESTATAL"),
    ("42", "ENTE_42", "PATRONATO PARA LAS EXPOSICIONES Y FERIAS EN LA CIUDAD DE TLAXCALA", "P_FERIA", "PATRONATO", "ESTATAL"),
]

def cargar_entes():
    """Carga los entes en la base de datos"""
    app = create_app('development')

    with app.app_context():
        print("=" * 60)
        print("CARGA DE CATÁLOGO DE ENTES")
        print("=" * 60)
        print()

        # Verificar cuántos entes ya existen
        entes_existentes = Ente.query.count()
        print(f"Entes actuales en BD: {entes_existentes}")
        print()

        if entes_existentes > 0:
            respuesta = input("¿Desea eliminar los entes existentes y recargar? (s/n): ")
            if respuesta.lower() == 's':
                Ente.query.delete()
                db.session.commit()
                print("✓ Entes existentes eliminados")
            else:
                print("Operación cancelada")
                return

        print()
        print(f"Cargando {len(ENTES_DATA)} entes...")
        print()

        entes_cargados = 0
        errores = 0

        for clave, codigo, nombre, siglas, tipo, ambito in ENTES_DATA:
            try:
                ente = Ente(
                    clave=clave,
                    codigo=codigo,
                    nombre=nombre,
                    siglas=siglas,
                    tipo=tipo,
                    ambito=ambito,
                    activo=True
                )
                db.session.add(ente)
                entes_cargados += 1
                print(f"✓ {clave:6} | {siglas:15} | {nombre[:50]}")
            except Exception as e:
                errores += 1
                print(f"✗ Error en {clave}: {str(e)}")

        try:
            db.session.commit()
            print()
            print("=" * 60)
            print(f"✓ Carga completada exitosamente")
            print(f"  Entes cargados: {entes_cargados}")
            print(f"  Errores: {errores}")
            print("=" * 60)
        except Exception as e:
            db.session.rollback()
            print()
            print(f"✗ Error al guardar en la base de datos: {str(e)}")

if __name__ == "__main__":
    cargar_entes()
